#!/usr/bin/env bash
# sync-sandbox-routes.sh — regenerate Caddy per-sandbox routes + forward watchdogs.
#
# Reads the current list of sandboxes (from `openshell sandbox list`) and
# emits one Caddy handle block per sandbox at /etc/caddy/conf.d/sandboxes.conf,
# then ensures a systemd watchdog is active per sandbox.
#
# No sandbox names are hardcoded — everything is derived at runtime.

set -euo pipefail

export PATH="$PATH:/root/.local/bin:$HOME/.local/bin"

CONF=/etc/caddy/conf.d/sandboxes.conf
GATEWAY_PORT="${GATEWAY_PORT:-18789}"

log() { printf '[routes-sync] %s\n' "$*"; }

# Collect active sandbox names.
#   `openshell sandbox list` prints a human-readable table whose first column
#   (after the "NAME" header row) is the sandbox name.
mapfile -t SANDBOXES < <(
  openshell sandbox list 2>/dev/null \
    | awk 'NR>1 && $1 != "" && $1 !~ /^[-=]+$/ { print $1 }'
)

if [ ${#SANDBOXES[@]} -eq 0 ]; then
  log "no sandboxes found — writing empty conf"
  printf '# Auto-generated by diffract — no active sandboxes (%s)\n' "$(date -u +%FT%TZ)" > "$CONF"
  systemctl reload caddy || true
fi

log "found ${#SANDBOXES[@]} sandbox(es): ${SANDBOXES[*]}"

# Generate Caddy conf
{
  printf '# Auto-generated by diffract (%s) — DO NOT EDIT MANUALLY\n' "$(date -u +%FT%TZ)"
  printf '# Regenerated by scripts/sync-sandbox-routes.sh after every onboard\n\n'
  for name in "${SANDBOXES[@]}"; do
    cat <<EOF
# Sandbox: ${name}

# WebSocket upgrades on the sandbox root — OpenClaw uses the base path as WS
# endpoint; these MUST bypass the Next.js HTML-injection route.
@${name}_ws {
    path /${name}/oc /${name}/oc/*
    header Connection *Upgrade*
    header Upgrade websocket
}
handle @${name}_ws {
    uri strip_prefix /${name}/oc
    reverse_proxy 127.0.0.1:${GATEWAY_PORT} {
        header_up Host 127.0.0.1:${GATEWAY_PORT}
        header_up Origin http://127.0.0.1:${GATEWAY_PORT}
    }
}

# HTML root — goes through Next.js to inject base path
@${name}_root path /${name}/oc /${name}/oc/
handle @${name}_root {
    rewrite * /dashboard/api/oc/${name}
    reverse_proxy 127.0.0.1:3000
}

# Assets, API calls, anything else under /<name>/oc/* → direct to gateway
handle /${name}/oc/* {
    uri strip_prefix /${name}/oc
    reverse_proxy 127.0.0.1:${GATEWAY_PORT} {
        header_up Host 127.0.0.1:${GATEWAY_PORT}
        header_up Origin http://127.0.0.1:${GATEWAY_PORT}
        header_down -X-Frame-Options
    }
}

EOF
  done
} > "$CONF"

# Reload Caddy
if systemctl reload caddy 2>/dev/null; then
  log "caddy reloaded"
else
  log "caddy reload failed — continuing"
fi

# Install the forward watchdog binary + systemd template (idempotent).
# The watchdog supervises `openshell forward` with an HTTP probe so it
# detects app-layer silent death (mulch mx-527903) that a PID-only check
# would miss.
WATCHDOG_BIN=/usr/local/bin/diffract-forward-watchdog.sh
WATCHDOG_SRC="${DIFFRACT_REPO_DIR:-/opt/diffract/repo}/scripts/diffract-forward-watchdog.sh"
if [ ! -x "$WATCHDOG_BIN" ] || ! cmp -s "$WATCHDOG_BIN" "$WATCHDOG_SRC" 2>/dev/null; then
  if [ -f "$WATCHDOG_SRC" ]; then
    log "installing $WATCHDOG_BIN from repo"
    install -m 0755 "$WATCHDOG_SRC" "$WATCHDOG_BIN"
  else
    log "WARN: $WATCHDOG_SRC not found — watchdog may not work"
  fi
fi

TEMPLATE=/etc/systemd/system/diffract-forward-watchdog@.service
if [ ! -f "$TEMPLATE" ]; then
  log "installing systemd template $TEMPLATE"
  cat > "$TEMPLATE" <<UNITEOF
[Unit]
Description=Diffract openshell-forward watchdog (HTTP-probe) for %i
After=network-online.target docker.service
Wants=network-online.target

[Service]
Type=simple
User=root
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/bin
ExecStart=${WATCHDOG_BIN} %i ${GATEWAY_PORT}
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
UNITEOF
  systemctl daemon-reload
fi

# Retire any previously-installed gateway-bridge units — they don't work on
# OpenShell's nested netns architecture (kubectl port-forward targets the
# outer pod, not the inner sandbox netns where openclaw-gateway actually
# listens). The simple ssh-forward watchdog is the right layer.
if [ -f /etc/systemd/system/diffract-gateway-bridge@.service ]; then
  log "retiring deprecated diffract-gateway-bridge units"
  while read -r unit _rest; do
    [ -z "$unit" ] && continue
    case "$unit" in diffract-gateway-bridge@*) ;;
      *) continue ;;
    esac
    systemctl stop "$unit" >/dev/null 2>&1 || true
    systemctl disable "$unit" >/dev/null 2>&1 || true
  done < <(systemctl list-units --all --no-legend --no-pager --type=service 2>/dev/null \
           | awk '/^ *diffract-gateway-bridge@/ {print $1}')
  rm -f /etc/systemd/system/diffract-gateway-bridge@.service
  rm -f /usr/local/bin/diffract-gateway-bridge.sh
  systemctl daemon-reload
fi

# Enable + start a watchdog per sandbox.
# `diffract onboard` starts its own `openshell forward` during step 2 — the
# watchdog leaves it alone if the HTTP probe already passes, or takes over
# if it's already dying.
for name in "${SANDBOXES[@]}"; do
  unit="diffract-forward-watchdog@${name}.service"
  if systemctl is-active --quiet "$unit"; then
    log "$unit already running"
  else
    log "starting $unit"
    systemctl enable --now "$unit" >/dev/null 2>&1 || true
  fi
done

# Disable watchdogs for sandboxes that no longer exist
if command -v systemctl >/dev/null; then
  mapfile -t ACTIVE_UNITS < <(systemctl list-units --no-legend --no-pager --type=service \
      | awk '/^ *diffract-forward-watchdog@/ {print $1}')
  for unit in "${ACTIVE_UNITS[@]}"; do
    inst="${unit#diffract-forward-watchdog@}"
    inst="${inst%.service}"
    keep=0
    for name in "${SANDBOXES[@]}"; do [ "$name" = "$inst" ] && keep=1; done
    if [ $keep -eq 0 ]; then
      log "stopping stale watchdog $unit"
      systemctl disable --now "$unit" >/dev/null 2>&1 || true
    fi
  done
fi

log "done"
