export const browserCoreExamples = [
  "diffraction browser status",
  "diffraction browser start",
  "diffraction browser stop",
  "diffraction browser tabs",
  "diffraction browser open https://example.com",
  "diffraction browser focus abcd1234",
  "diffraction browser close abcd1234",
  "diffraction browser screenshot",
  "diffraction browser screenshot --full-page",
  "diffraction browser screenshot --ref 12",
  "diffraction browser snapshot",
  "diffraction browser snapshot --format aria --limit 200",
  "diffraction browser snapshot --efficient",
  "diffraction browser snapshot --labels",
];

export const browserActionExamples = [
  "diffraction browser navigate https://example.com",
  "diffraction browser resize 1280 720",
  "diffraction browser click 12 --double",
  'diffraction browser type 23 "hello" --submit',
  "diffraction browser press Enter",
  "diffraction browser hover 44",
  "diffraction browser drag 10 11",
  "diffraction browser select 9 OptionA OptionB",
  "diffraction browser upload /tmp/diffraction/uploads/file.pdf",
  'diffraction browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "diffraction browser dialog --accept",
  'diffraction browser wait --text "Done"',
  "diffraction browser evaluate --fn '(el) => el.textContent' --ref 7",
  "diffraction browser console --level error",
  "diffraction browser pdf",
];
