apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diffraction-home-pvc
  labels:
    app: diffraction
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
