import { Router } from "express";
import { execSync } from "node:child_process";
import fs from "node:fs";

const router = Router();

const CADDY_TEMPLATE_PATH = "/root/diffract/deploy/caddy/Caddyfile";
const CADDY_SANDBOX_CONF_PATH = "/etc/caddy/conf.d/sandboxes.conf";
if (!process.env.DIFFRACT_DOMAIN) {
  throw new Error("DIFFRACT_DOMAIN environment variable is required — set it to your VPS hostname (e.g. export DIFFRACT_DOMAIN=yourhost.hstgr.cloud)");
}
const DOMAIN = process.env.DIFFRACT_DOMAIN;

/** Parse `openshell forward list` to get sandbox → port mapping */
function getForwardedPorts() {
  try {
    const output = execSync(
      'export PATH="$PATH:$HOME/.local/bin"; openshell forward list 2>/dev/null',
      { encoding: "utf-8", timeout: 5000 }
    );
    const lines = output.split("\n").filter((l) => l.trim() && !l.startsWith("SANDBOX"));
    return lines.map((line) => {
      // SANDBOX      BIND      PORT     PID        STATUS
      const cols = line.trim().split(/\s+/);
      return {
        name: cols[0],
        bind: cols[1] || "127.0.0.1",
        port: parseInt(cols[2], 10),
        pid: cols[3],
        status: (cols[4] || "").replace(/\x1b\[[0-9;]*m/g, ""),
      };
    }).filter((f) => f.name && f.port && f.status === "running");
  } catch {
    return [];
  }
}

// GET /api/gateway-routes — returns all sandbox gateway routes
router.get("/", (_req, res) => {
  const forwards = getForwardedPorts();
  res.json({
    domain: DOMAIN,
    routes: forwards.map((f) => ({
      sandbox: f.name,
      port: f.port,
      url: `/agent/${f.name}/`,
      chatUrl: `/sandboxes/${f.name}/diffract_chat/`,
    })),
  });
});

// GET /api/gateway-routes/:name — returns a single sandbox's gateway route
router.get("/:name", (req, res) => {
  const forwards = getForwardedPorts();
  const match = forwards.find((f) => f.name === req.params.name);
  if (!match) {
    res.status(404).json({ error: `No active gateway for sandbox '${req.params.name}'` });
    return;
  }
  res.json({
    sandbox: match.name,
    port: match.port,
    url: `/agent/${match.name}/`,
    chatUrl: `/sandboxes/${match.name}/diffract_chat/`,
  });
});

// POST /api/gateway-routes/sync — regenerate sandbox Caddy config from active sandboxes
// Writes only the per-sandbox handle blocks to /etc/caddy/conf.d/sandboxes.conf.
// The main /etc/caddy/Caddyfile is static and imports conf.d/*.conf — never overwritten here.
router.post("/sync", (_req, res) => {
  try {
    const forwards = getForwardedPorts();
    const sandboxConf = generateSandboxConf(forwards);
    fs.mkdirSync("/etc/caddy/conf.d", { recursive: true });
    fs.writeFileSync(CADDY_SANDBOX_CONF_PATH, sandboxConf, "utf-8");
    execSync("systemctl reload caddy 2>&1", { timeout: 5000 });
    res.json({ ok: true, routes: forwards.length, reloaded: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// generateSandboxConf generates only the per-sandbox handle blocks.
// This file is imported by /etc/caddy/Caddyfile via `import /etc/caddy/conf.d/*.conf`.
// The main Caddyfile owns the server block, static routes, and marketing blocks — never
// overwritten by this function.
function generateSandboxConf(forwards) {
  if (forwards.length === 0) {
    return `# Auto-generated by Diffract — no active sandboxes\n# Generated at: ${new Date().toISOString()}\n`;
  }

  const blocks = forwards.map((f) => `
	# Sandbox: ${f.name} (port ${f.port})
	handle /agent/${f.name}/* {
		uri strip_prefix /agent/${f.name}
		reverse_proxy 127.0.0.1:${f.port} {
			header_up Host 127.0.0.1:${f.port}
			header_up Origin http://127.0.0.1:${f.port}
			header_down -X-Frame-Options
			header_down Content-Security-Policy "default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors https://${DOMAIN}; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' ws: wss: https://${DOMAIN};"
		}
	}
	handle /agent/${f.name} {
		redir /agent/${f.name}/ permanent
	}
	handle /sandboxes/${f.name}/diffract_chat/* {
		uri strip_prefix /sandboxes/${f.name}/diffract_chat
		reverse_proxy 127.0.0.1:${f.port} {
			header_up Host 127.0.0.1:${f.port}
			header_up Origin http://127.0.0.1:${f.port}
			header_down -X-Frame-Options
			header_down Content-Security-Policy "default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors https://${DOMAIN}; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' ws: wss: https://${DOMAIN};"
		}
	}
	handle /sandboxes/${f.name}/diffract_chat {
		redir /sandboxes/${f.name}/diffract_chat/ permanent
	}`).join("\n");

  return `# Auto-generated by Diffract — DO NOT EDIT MANUALLY
# Managed by POST /api/gateway-routes/sync (api/routes/gateway-routes.js)
# Generated at: ${new Date().toISOString()}
# Sandboxes: ${forwards.map((f) => f.name).join(", ")}
# Imported by /etc/caddy/Caddyfile via: import /etc/caddy/conf.d/*.conf
${blocks}
`;
}

// GET /api/gateway-routes/:name/embed — HTML page that bootstraps the OpenClaw UI
// Sets window.__OPENCLAW_CONTROL_UI_BASE_PATH__ so API calls route correctly
router.get("/:name/embed", (req, res) => {
  const forwards = getForwardedPorts();
  const match = forwards.find((f) => f.name === req.params.name);
  if (!match) {
    res.status(404).send("No active gateway for this sandbox");
    return;
  }
  // The embed page loads at /agent/<name>/ and sets the base path
  // so OpenClaw UI makes API calls to /agent/<name>/__openclaw/api/v1/*
  const basePath = `/agent/${match.name}`;
  res.setHeader("Content-Type", "text/html");
  res.send(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${match.name} — Diffract Agent</title>
<style>html,body{margin:0;padding:0;height:100%;overflow:hidden}iframe{width:100%;height:100%;border:none}</style>
</head>
<body>
<iframe src="${basePath}/" allow="clipboard-write; clipboard-read"></iframe>
<script>
// Inject base path into the iframe once it loads
const iframe = document.querySelector('iframe');
iframe.addEventListener('load', () => {
  try {
    iframe.contentWindow.__OPENCLAW_CONTROL_UI_BASE_PATH__ = '${basePath}';
  } catch(e) { /* cross-origin, handled by gateway */ }
});
</script>
</body>
</html>`);
});

export default router;
